WIP: Fix the error output of SQL Methods
zopefoundation/Products.ZSQLMethods pull request #33
Opened 2021-01-07 13:38 UTC by jan-jockusch

The error output uses `__repr__()`, which in Zope2 was inherited from SimpleItem.Item, which in turn pulls in `SimpleItem.PathReprProvider`.

This inheritance pattern does not work in the same way in Python3, losing PathReprProvider in DA. Adding it there, at the very first position, yields the correct output.

Test this with:

    >>> from Products.ZSQLMethods.SQL import SQL
    >>> x = SQL('a', 'a', 'a', '', 'select * from data')
    >>> repr(x)
    '<SQL at a>'

2021-01-07 13:39 UTC, jan-jockusch commented
I'd like to add the test into the project, to stabilize the code. This is not yet done, therefore the PR is "WIP".

2021-01-07 14:40 UTC, jan-jockusch commented
Test included. Ready for review.

2021-01-08 06:17 UTC, jan-jockusch commented
@dataflake Happy New Year! I have no idea if the request for review is the correct thing to do at this point. If I misbehaved by clicking on the request link, you're welcome to ignore me. I don't know the PR workflow on github yet, but it's good to hear there's a "draft" mode, that's clearer than the WIP prefix.

2021-01-08 07:15 UTC, icemac requested changes
LGTM, an additional entry in the change log would make the PR perfect.

2021-01-08 07:23 UTC, jan-jockusch commented
@icemac Thanks for reviewing!

CHANGES entry added. Shall I squash the commits or should they stay this way?

2021-01-08 07:24 UTC, icemac commented on CHANGES.rst
> +- Fix the error outout of SQL Methods
```suggestion
- Fix the ``repr`` of SQL Methods.
```

2021-01-08 07:24 UTC, icemac commented
I'd prefer squashing the commits.

2021-01-08 07:28 UTC, icemac approved these changes
LGTM.

2021-01-09 10:08 UTC, dataflake approved these changes
@jan-jockusch Happy New Year to you, too! Requesting a PR is totally fine, thanks for your help!

2021-01-09 10:08 UTC, merged

2021-01-09 10:14 UTC, dataflake commented
I just released version 3.12 with the fix.